theme = "gruvbox"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"C-g" = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
