["plugins/pure"]
  type = "archive"
  url = "https://github.com/sindresorhus/pure/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
["plugins/zephyr"]
  type = "archive"
  url = "https://github.com/mattmc3/zephyr/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
["plugins/zsh-completions"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
["plugins/fast-syntax-highlighting"]
  type = "archive"
  url = "https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
["plugins/zsh-history-substring-search"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-history-substring-search/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
["plugins/zsh-autosuggestions"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
["plugins/zsh-defer"]
  type = "archive"
  url = "https://github.com/romkatv/zsh-defer/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
