theme = "modern"
icons = "material-nf"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
clickable = false

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "rofication"
interval = 1
socket_path = "/tmp/rofi_notification_daemon"

[[block]]
block = "kdeconnect"
bat_good = 60

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
