#!/usr/bin/env bash
typeset -A menu

uptime=$(uptime -p | sed -e 's/up //g')

menu=(
  [ Shutdown]="poweroff"
  [ Restart]="reboot"
  [ Lock]="~/.config/i3/blur-lock"
  [ Sleep]="suspend"
  [ Exit]="i3-msg exit"
)

selection="$(printf '%s\n' "${!menu[@]}" | rofi -dmenu -theme-str '#listview {lines: 5;}' -p "Uptime: $uptime")"

exec ${menu[${selection}]}
